### ISSUE TITLE
Quicktime error when trying to run tikatko

### ISSUE THREAD

**Issue by jackiekazil** [pyvec/tikatko#1]
I tried to run this & I got the following error: 

```
$ tikatko
```

```
OSError: dlopen(/System/Library/Frameworks/QuickTime.framework/QuickTime, 6): no suitable image found.  Did find:
    /System/Library/Frameworks/QuickTime.framework/QuickTime: mach-o, but wrong architecture
    /System/Library/Frameworks/QuickTime.framework/QuickTime: mach-o, but wrong architecture
```

I am running OSX Version 10.9.2

**Comment by encukou** [comment]
Unfortunately I don't have OS X available so I can't reproduce this issue.
Is that the full traceback you're getting?
What is the Pyglet version you're using? Can you check if Pyglet itself runs for you -- for example with http://www.pyglet.org/doc/programming_guide/hello_world.py ?

**Comment by jackiekazil** [comment]
Here is the full traceback... 

```
Traceback (most recent call last):
  File "/Users/jkazil/Projects/envs/test/bin/tikatko", line 9, in <module>
    load_entry_point('tikatko==0.1', 'console_scripts', 'tikatko')()
  File "/Users/jkazil/Projects/envs/test/lib/python2.7/site-packages/pkg_resources.py", line 353, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/jkazil/Projects/envs/test/lib/python2.7/site-packages/pkg_resources.py", line 2321, in load_entry_point
    return ep.load()
  File "/Users/jkazil/Projects/envs/test/lib/python2.7/site-packages/pkg_resources.py", line 2048, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Users/jkazil/Projects/envs/test/lib/python2.7/site-packages/tikatko.py", line 17, in <module>
    from gillcup_graphics import Layer, Text, Rectangle, Window, RealtimeClock, run
  File "/Users/jkazil/Projects/envs/test/lib/python2.7/site-packages/gillcup_graphics/__init__.py", line 39, in <module>
    from gillcup_graphics.objects import (
  File "/Users/jkazil/Projects/envs/test/lib/python2.7/site-packages/gillcup_graphics/objects.py", line 562, in <module>
    class Rectangle(GraphicsObject):
  File "/Users/jkazil/Projects/envs/test/lib/python2.7/site-packages/gillcup_graphics/objects.py", line 568, in Rectangle
    vertices = (gl.GLfloat * 8)(0, 0, 1, 0, 0, 1, 1, 1)
  File "/Users/jkazil/Projects/envs/test/lib/python2.7/site-packages/pyglet/__init__.py", line 306, in __getattr__
    __import__(import_name)
  File "/Users/jkazil/Projects/envs/test/lib/python2.7/site-packages/pyglet/gl/__init__.py", line 510, in <module>
    import pyglet.window
  File "/Users/jkazil/Projects/envs/test/lib/python2.7/site-packages/pyglet/window/__init__.py", line 1669, in <module>
    from pyglet.window.carbon import CarbonPlatform, CarbonWindow
  File "/Users/jkazil/Projects/envs/test/lib/python2.7/site-packages/pyglet/window/carbon/__init__.py", line 69, in <module>
    framework='/System/Library/Frameworks/QuickTime.framework')
  File "/Users/jkazil/Projects/envs/test/lib/python2.7/site-packages/pyglet/lib.py", line 90, in load_library
    return self.load_framework(kwargs['framework'])
  File "/Users/jkazil/Projects/envs/test/lib/python2.7/site-packages/pyglet/lib.py", line 226, in load_framework
    lib = ctypes.cdll.LoadLibrary(realpath)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/System/Library/Frameworks/QuickTime.framework/QuickTime, 6): no suitable image found.  Did find:
    /System/Library/Frameworks/QuickTime.framework/QuickTime: mach-o, but wrong architecture
    /System/Library/Frameworks/QuickTime.framework/QuickTime: mach-o, but wrong architecture
```

RE: What is the Pyglet version you're using? Can you check if Pyglet itself runs for you -- for example with http://www.pyglet.org/doc/programming_guide/hello_world.py ?
pyglet==1.1.4

```
In [1]: import pyglet

In [2]: window = pyglet.window.Window()
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-2-35f8b45d96a8> in <module>()
----> 1 window = pyglet.window.Window()

/Users/jkazil/Projects/envs/test/lib/python2.7/site-packages/pyglet/__init__.pyc in __getattr__(self, name)
    304
    305             import_name = 'pyglet.%s' % self._module_name
--> 306             __import__(import_name)
    307             module = sys.modules[import_name]
    308             object.__setattr__(self, '_module', module)

/Users/jkazil/Projects/envs/test/lib/python2.7/site-packages/pyglet/window/__init__.py in <module>()
   1667     # Try to determine which platform to use.
   1668     if sys.platform == 'darwin':
-> 1669         from pyglet.window.carbon import CarbonPlatform, CarbonWindow
   1670         _platform = CarbonPlatform()
   1671         Window = CarbonWindow

/Users/jkazil/Projects/envs/test/lib/python2.7/site-packages/pyglet/window/carbon/__init__.py in <module>()
     67     framework='/System/Library/Frameworks/Carbon.framework')
     68 quicktime = pyglet.lib.load_library(
---> 69     framework='/System/Library/Frameworks/QuickTime.framework')
     70
     71 carbon.GetEventDispatcherTarget.restype = EventTargetRef

/Users/jkazil/Projects/envs/test/lib/python2.7/site-packages/pyglet/lib.pyc in load_library(self, *names, **kwargs)
     88         '''
     89         if 'framework' in kwargs and self.platform == 'darwin':
---> 90             return self.load_framework(kwargs['framework'])
     91
     92         platform_names = kwargs.get(self.platform, [])

/Users/jkazil/Projects/envs/test/lib/python2.7/site-packages/pyglet/lib.pyc in load_framework(self, path)
    224         realpath = self.find_framework(path)
    225         if realpath:
--> 226             lib = ctypes.cdll.LoadLibrary(realpath)
    227             if _debug_lib:
    228                 print realpath

/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.pyc in LoadLibrary(self, name)
    441
    442     def LoadLibrary(self, name):
--> 443         return self._dlltype(name)
    444
    445 cdll = LibraryLoader(CDLL)

/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.pyc in __init__(self, name, mode, handle, use_errno, use_last_error)
    363
    364         if handle is None:
--> 365             self._handle = _dlopen(self._name, mode)
    366         else:
    367             self._handle = handle

OSError: dlopen(/System/Library/Frameworks/QuickTime.framework/QuickTime, 6): no suitable image found.  Did find:
    /System/Library/Frameworks/QuickTime.framework/QuickTime: mach-o, but wrong architecture
    /System/Library/Frameworks/QuickTime.framework/QuickTime: mach-o, but wrong architecture
```

**Comment by encukou** [comment]
After some googling, I found this Pyglet issue https://code.google.com/p/pyglet/issues/detail?id=438
It lists some workarounds you might try.

**Comment by encukou** [comment]
timeout
